# Generated by Django 5.1.4 on 2025-01-13 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_alter_hotelpartnerlist_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hotelpartnerlist',
            table='hotelpartner',
        ),
    ]
