# Generated by Django 5.1.4 on 2025-01-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_alter_hotelpartnerlist_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelpartnerlist',
            name='CITY',
            field=models.TextField(default='Nagpur', max_length=100),
        ),
    ]
