# Generated by Django 5.1.4 on 2025-01-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_hotelpartnerlist_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelpartnerlist',
            name='CITY',
            field=models.TextField(max_length=100),
        ),
    ]
