# Generated by Django 5.1.4 on 2025-01-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0007_alter_hotelpartnerlist_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelpartnerlist',
            name='IMAGE',
            field=models.ImageField(default='Image', upload_to=''),
        ),
    ]
