# Generated by Django 5.1.4 on 2025-01-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0008_hotelpartnerlist_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelCities',
            fields=[
                ('CITYID', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('CITY', models.TextField(max_length=100)),
            ],
            options={
                'db_table': 'hotelcities',
            },
        ),
    ]
