# Generated by Django 5.1.4 on 2025-01-12 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelPartner',
            fields=[
                ('HOTELID', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('HOTELNAME', models.TextField(max_length=100)),
                ('LOCATION', models.TextField(max_length=250)),
                ('CHECKIN', models.TextField(max_length=30)),
                ('CHECKOUT', models.TextField(max_length=30)),
                ('AMENITIES', models.TextField(max_length=100)),
            ],
        ),
    ]
