# Generated by Django 5.1.4 on 2025-01-12 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0002_alter_hotelpartner_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HotelPartner',
        ),
    ]
